name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Teststeps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Verify hello action works
        uses: ./
